pipeline {
    agent {
        docker {
            image 'node:16-alpine'
            args '-v /c/ProgramData/Jenkins/.jenkins/workspace/pp:/workspace -w /workspace'
        }
    }
    stages {
        stage('Run') {
            steps {
                sh 'node --version'
            }
        }
    }
}

